export const NotificationTypes = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
  TASK_OVERDUE: 'TASK_OVERDUE',
  STATUS_CHANGED: 'STATUS_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  MENTION: 'MENTION',
  TEAM_UPDATE: 'TEAM_UPDATE'
}; 